# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCREATE():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cREATE(self):
    self.driver.get("https://auth.cac.dk/Account/Login")
    self.driver.set_window_size(1728, 1055)
    self.driver.find_element(By.ID, "inputEmail").send_keys("TAthomas")
    self.driver.find_element(By.ID, "inputPassword").click()
    self.driver.find_element(By.ID, "inputPassword").send_keys("TAthomas77")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.LINK_TEXT, "Åben kundestyring").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".nav > li:nth-child(5) > a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".navigation-dropdown-menu > li:nth-child(1) > a").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ag-row-first .ev-badge").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ag-cell-focus .ng-untouched").click()
  
